### ISSUE TITLE
One issue about R_cam2rect

### ISSUE THREAD

**Issue by zhchyang2004** [leofansq/Tools_Merge_Image_PointCloud#1]
Hi, 

In Line217&218 func.py,  a transformation 4x4 is composed from R_cam2rect.  Why '1' is located in [0,0] instead of [3,3]?  But the points from Line 273 is a normal homogeneous coordination with '1' at the end instead of the beginning.

It's very strange. Could you please share your idea?

Thanks!

**Comment by leofansq** [comment]
Thank you for pointing out that! I have corrected the mistakes and updated the code.
